---
- name: Playbook for initialising the nodes
  hosts: pi-cluster
  gather_facts: yes
  tasks:
    - name: Initialise node
      shell: /home/pi/prowler/start.sh
      ignore_errors: false
      become: true
