---
- name: Playbook for rebooting the RPis
  hosts: pi-cluster
  gather_facts: no
  tasks:
    - name: 'Reboot RPi'
      shell: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
      become: true

    - name: "Wait for reboot to complete"
      local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
      become: false
